# Dependencies
#markdown: karmdown
#pygments:         true

#highlighter: rouge

# Permalinks
permalink:        :title

# Setup
name:             Novellatranslation
title:            Novellatranslation
tagline:          'Chinese Novels '
description:      'Chinese novel translated in English'
url:              http://novellatranslation.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon

excerpt_separator: <!--more-->

gems:
  - jekyll-sitemap
